version: "3.9"
services:
  cdm:
    build: ./CDM
    env_file: [env]
    ports:
      - 5432:5432
    container_name: cdm
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 0.0.0.0"]
      interval: 15s
      timeout: 5s
      retries: 180
  broadsea-webtools:
    build: ./broadsea-webtools
    container_name: broadsea-webtools
    ports:
      - 8080:8080
    env_file: [env]
    environment:
      - security_enabled=false
      - security_origin=*
    depends_on:
      cdm:
        condition: service_healthy
      