version: 3.9
services:
  cdm:
    build: ./CDM
    env_file: [env]
    port:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 5s
      timeout: 5s
      retry: 5
